### ISSUE TITLE
Program Useage

### ISSUE THREAD

**Issue by simmershred** [codethug/SimpleTv#20]
Hi,  your program is exactly what I am looking for but I am having problems with two use cases.  

1) When I use the the -d option the program makes the save directory in the same directory as the program resides.  The program seems to change something like "c:\tvshows" to "c_tvshows"

![image](https://cloud.githubusercontent.com/assets/18036893/14049256/45d36cfc-f271-11e5-8a00-f11cb9a56669.png)

2) The wildcard for shows -s is not working for me.  If I use NCIS\* or Survivor\*   (in quotes) it does not seem to start downloading any shows.  The program just ends.  If I do not use the -s  it will start downloading the first show on the STV.

![image](https://cloud.githubusercontent.com/assets/18036893/14049264/598842a4-f271-11e5-911a-391d2fbfb425.png)

**Comment by timlarson345** [comment]
Bug Fixed in 712a6510bbb7409793015e54490d1012b319e891.  Download the latest version to verify that this takes care of the problem for you.

**Comment by timlarson345** [comment]
If you are still having problems with this, please:
- describe the problem again (feel free to summarize if it's the same as above)
- try the download again with the `-l` flag
- attach the resulting log file to this issue
