### ISSUE TITLE
Ability to Skip a DVR for downloading Recordings  Or selecting the DVR we want  

### ISSUE THREAD

**Issue by richpel** [codethug/SimpleTv#31]
Add a command line switch where a specific DVR can be chosen, perhaps using similar syntax for choosing a show (allowing wildcards, etc.).

It might also be helpful to provide a command where you can list the DVRs that are found to make it easier to know exactly what the names  of the DVRs are.

**Comment by timlarson345** [comment]
Great idea.  I added a description with some other similar ideas.

**Comment by timlarson345** [comment]
Fixed in release 0.3.10 by 2cef5c7e
